# # Generated by using Rcpp::compileAttributes() -> do not edit by hand
# # Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

# sharkfin <- function(Y, X, prob_vec, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE) {
#     .Call('_bayeslm_sharkfin', PACKAGE = 'bayeslm', Y, X, prob_vec, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, verb, icept, standardize, singular)
# }

# bayeslm <- function(Y, X, beta_hat, beta, penalize, block_vec, rank_vec, prior_type = 1L, user_prior_function = NULL, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE) {
#     .Call('_bayeslm_bayeslm', PACKAGE = 'bayeslm', Y, X, beta_hat, beta, penalize, block_vec, rank_vec, prior_type, user_prior_function, sigma, s2, kap2, nsamps, burn, skip, vglobal, verb, icept, standardize, singular)
# }

# blasso <- function(Y, X, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE) {
#     .Call('_bayeslm_blasso', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, verb, icept, standardize, singular)
# }

# horseshoe <- function(Y, X, penalize, block_vec, prior_type = 1L, user_prior_function = NULL, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE) {
#     .Call('_bayeslm_horseshoe', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, user_prior_function, sigma, s2, kap2, nsamps, burn, skip, vglobal, verb, icept, standardize, singular)
# }

# nonlocal <- function(Y, X, prior_mean, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE) {
#     .Call('_bayeslm_nonlocal', PACKAGE = 'bayeslm', Y, X, prior_mean, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, verb, icept, standardize, singular)
# }

# ridge <- function(Y, X, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE) {
#     .Call('_bayeslm_ridge', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, verb, icept, standardize, singular)
# }

horseshoe_cpp_loop = function(Y, X, penalize, block_vec, prior_type, user_prior_function, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc){
            .Call('bayeslm_horseshoe', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, user_prior_function, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

blasso_cpp_loop = function(Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc){
            .Call('bayeslm_blasso', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

bridge_cpp_loop = function(Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc){
            .Call('bayeslm_ridge', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

nonlocal_cpp_loop = function(Y, X, prior_mean, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc){
            .Call('bayeslm_nonlocal', PACKAGE = 'bayeslm', Y, X, prior_mean, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

sharkfin_cpp_loop = function(Y, X, prob_vec, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc){
            .Call('bayeslm_sharkfin', PACKAGE = 'bayeslm', Y, X, prob_vec, penalize, block_vec, prior_type, sigma, s2, kap2, N, burnin, thinning, vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}


# hs_gibbs_no_scaling <- function(Y, X, nsamps = 1000L, a = 1, b = 1, scale_sigma_prior = TRUE) {
#     .Call('bayeslm_hs_gibbs_no_scaling', PACKAGE = 'bayeslm', Y, X, nsamps, a, b, scale_sigma_prior)
# }

hs_gibbs <- function(Y, X, nsamps = 1000L, a = 1, b = 1, scale_sigma_prior = TRUE) {
    .Call('bayeslm_hs_gibbs', PACKAGE = 'bayeslm', Y, X, nsamps, a, b, scale_sigma_prior)
}

hs_gibbs_2 <- function(Y, X, nsamps = 1000L, a = 1, b = 1, scale_sigma_prior = TRUE) {
    .Call('bayeslm_hs_gibbs_2', PACKAGE = 'bayeslm', Y, X, nsamps, a, b, scale_sigma_prior)
}
