# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sharkfin_cpp_loop <- function(Y, X, prob_vec, penalize, block_vec, cc, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_sharkfin_cpp_loop`, Y, X, prob_vec, penalize, block_vec, cc, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior)
}

bayeslm_cpp_loop <- function(Y, X, penalize, block_vec, cc, prior_type = 1L, user_prior_function = NULL, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_bayeslm_cpp_loop`, Y, X, penalize, block_vec, cc, prior_type, user_prior_function, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior)
}

blasso_cpp_loop <- function(Y, X, penalize, block_vec, cc, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_blasso_cpp_loop`, Y, X, penalize, block_vec, cc, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior)
}

hs_gibbs <- function(Y, X, nsamps = 1000L, a = 1, b = 1, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_hs_gibbs`, Y, X, nsamps, a, b, scale_sigma_prior)
}

hs_gibbs_2 <- function(Y, X, nsamps = 1000L, a = 1, b = 1, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_hs_gibbs_2`, Y, X, nsamps, a, b, scale_sigma_prior)
}

horseshoe_cpp_loop <- function(Y, X, penalize, block_vec, cc, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1.0, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_horseshoe_cpp_loop`, Y, X, penalize, block_vec, cc, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior)
}

inverseLaplace_cpp_loop <- function(Y, X, lambda, penalize, block_vec, cc, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_inverseLaplace_cpp_loop`, Y, X, lambda, penalize, block_vec, cc, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior)
}

nonlocal_cpp_loop <- function(Y, X, prior_mean, penalize, block_vec, cc, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_nonlocal_cpp_loop`, Y, X, prior_mean, penalize, block_vec, cc, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior)
}

bridge_cpp_loop <- function(Y, X, penalize, block_vec, cc, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE) {
    .Call(`_bayeslm_bridge_cpp_loop`, Y, X, penalize, block_vec, cc, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior)
}

