# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sharkfin <- function(Y, X, prob_vec, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE, cc) {
    .Call('_bayeslm_sharkfin', PACKAGE = 'bayeslm', Y, X, prob_vec, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

bayeslm <- function(Y, X, penalize, block_vec, prior_type = 1L, user_prior_function = NULL, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE, cc) {
    .Call('_bayeslm_bayeslm', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, user_prior_function, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

blasso <- function(Y, X, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE, cc) {
    .Call('_bayeslm_blasso', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

hs_gibbs_2 <- function(Y, X, nsamps = 1000L, a = 1, b = 1, scale_sigma_prior = TRUE) {
    .Call('_bayeslm_hs_gibbs_2', PACKAGE = 'bayeslm', Y, X, nsamps, a, b, scale_sigma_prior)
}

hs_gibbs <- function(Y, X, nsamps = 1000L, a = 1, b = 1, scale_sigma_prior = TRUE) {
    .Call('_bayeslm_hs_gibbs', PACKAGE = 'bayeslm', Y, X, nsamps, a, b, scale_sigma_prior)
}

horseshoe <- function(Y, X, penalize, block_vec, prior_type = 1L, user_prior_function = NULL, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1.0, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE, cc) {
    .Call('_bayeslm_horseshoe', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, user_prior_function, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

nonlocal <- function(Y, X, prior_mean, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal = TRUE, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE, cc) {
    .Call('_bayeslm_nonlocal', PACKAGE = 'bayeslm', Y, X, prior_mean, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

ridge <- function(Y, X, penalize, block_vec, prior_type = 1L, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 1L, vglobal = 1.0, sampling_vglobal, verb = FALSE, icept = FALSE, standardize = TRUE, singular = FALSE, scale_sigma_prior = TRUE, cc) {
    .Call('_bayeslm_ridge', PACKAGE = 'bayeslm', Y, X, penalize, block_vec, prior_type, sigma, s2, kap2, nsamps, burn, skip, vglobal, sampling_vglobal, verb, icept, standardize, singular, scale_sigma_prior, cc)
}

